---
booktitle: Proceedings of the 2nd Workshop on Online Recommder Systems and User Modeling
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
shortname: ORSUM
year: '2019'
volume: 109
start: 2019-09-19
end: 2019-09-19
url: https://proceedings.mlr.press
author:
  name: PMLR
published: 2019-10-14
sections:
- name: Keynote
  title: Keynote
- name: Contributed Papers
  title: Contributed Papers
layout: proceedings
publisher: PMLR
series: Proceedings of Machine Learning Research
issn: 2640-3498
id: ORSUM-2019
month: 0
cycles: false
bibtex_editor: Vinagre, Jo\~{a}o and Jorge, Al\'{i}pio M\'{a}rio and Bifet, Albert
  and Al-Ghossein, Marie
editor:
- given: João
  family: Vinagre
- given: Alípio Mário
  family: Jorge
- given: Albert
  family: Bifet
- given: Marie
  family: Al-Ghossein
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 2nd Workshop on Online Recommder Systems and User Modeling on 19 September 2019

  Published as Volume 109 by the Proceedings of Machine Learning Research on 14 October 2019.

  Volume Edited by:
    João Vinagre
    Alípio Mário Jorge
    Albert Bifet
    Marie Al-Ghossein

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 19 Sep
baseurl: "/v109"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
permalink: "/:title.html"
ghub:
  edit: true
  repository: v109
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: 2nd Workshop on Online Recommender Systems and User Modeling
  url: 
  location: ACM RecSys 2019, Copenhagen, Denmark
  dates:
  - 2019-09-19
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
